version: '3'

services:
  frontend:
    build:
        context: frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${MAIN_PORT:-80}:80
    volumes:
      - ./dummy-api/v0.0/:/var/www/api/v0.0/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
  database:
    image: git.phinion.com/phinion/dependency_proxy/containers/postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - .env
    ports:
      - 5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
