version: '3'

services:
  database:
    image: git.phinion.com/phinion/dependency_proxy/containers/postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    env_file:
      - .env
    ports:
      - 5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
