services:
  frontend:
    build:
      context: frontend
      args:
        VITE_REACT_APP_GIT_SHA: ${VITE_REACT_APP_GIT_SHA:-Whoops you forgot to set the commit hash}
        VITE_REACT_APP_DEPLOY_DATE: ${VITE_REACT_APP_DEPLOY_DATE:-Whoops you forgot to set the commit date}
        VITE_REACT_APP_VERSION_NUMBER: ${VITE_REACT_APP_VERSION_NUMBER:-Whoops you forgot to set version}
    develop:
      watch:
        - action: rebuild
          path: frontend
    restart: unless-stopped
    ports:
      - ${MAIN_PORT:-80}:80
    volumes:
      - ./dummy-api/v0.0/:/var/www/api/v0.0/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    env_file:
      - ./version.env

  backend:
    build:
      context: backend
    develop:
      watch:
        - action: rebuild
          path: backend
    restart: unless-stopped
    env_file:
      - path: default.env
      - path: .env
        required: true
    environment:
      BASE_URL: ${BASE_URL:-http://localhost:${MAIN_PORT}}
      DIWI_DB_HOST: ${DIWI_DB_HOST:-database}
      DIWI_DB_NAME: ${DIWI_DB_NAME:-diwi}
      DIWI_DB_USERNAME: ${DIWI_DB_USERNAME:-diwi}
      DIWI_DB_PASSWORD: ${DIWI_DB_PASSWORD:?define a password please}
      KC_REALM_NAME: ${KC_REALM_NAME:?oidc config needed}
      KC_AUTH_SERVER_URL: ${KC_AUTH_SERVER_URL:?oidc config needed}
      KC_SECRET: ${KC_SECRET:?oidc config needed}
      KC_RESOURCE_NAME: ${KC_RESOURCE_NAME:?oidc config needed}
      MUNICIPALITY_NAME: ${MUNICIPALITY_NAME:?Please set up a municipality name}
      DEFAULT_MAP_BOUNDS: ${DEFAULT_MAP_BOUNDS}
      MAIL_USERNAME: ${MAIL_USERNAME?-Please set up mail username}
      MAIL_PASSWORD: ${MAIL_PASSWORD?-Please set up mail password}
      MAIL_SMTP_HOST: ${MAIL_SMTP_HOST?-Please set up mail host}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT:-465}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH:-true}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS:-true}
      MAIL_SMTP_SSL: ${MAIL_SMTP_SSL:-true}
    volumes:
      - ./data/backend:/data
    ports:
      - ${BACKEND_PORT:-8080}
    depends_on:
      - database

  database:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DIWI_DB_NAME:-diwi}
      POSTGRES_USER: ${DIWI_DB_USERNAME:-diwi}
      POSTGRES_PASSWORD: ${DIWI_DB_PASSWORD:?define a password please}
    ports:
      - ${DATABASE_PORT:-5432}
    volumes:
      - ./data/database:/var/lib/postgresql/data
      - ./backup:/backup:ro
