version: "3"

services:
  frontend:
    build:
      context: frontend
    restart: unless-stopped
    ports:
      - ${MAIN_PORT:-80}:80
    volumes:
      - ./dummy-api/v0.0/:/var/www/api/v0.0/:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro

  backend:
    build:
      context: backend
    develop:
      watch:
        - action: rebuild
          path: backend
    restart: unless-stopped
    environment:
      DIWI_DB_HOST: ${DIWI_DB_HOST:-database}
      DIWI_DB_NAME: ${DIWI_DB_NAME:-diwi}
      DIWI_DB_USERNAME: ${DIWI_DB_USERNAME:-diwi}
      DIWI_DB_PASSWORD: ${DIWI_DB_PASSWORD?-define a password please}
    ports:
      - ${BACKEND_PORT:-8080}
    depends_on:
      - keycloak

  database:
    image: git.phinion.com/phinion/dependency_proxy/containers/postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DIWI_DB_NAME:-diwi}
      POSTGRES_USER: ${DIWI_DB_USERNAME:-diwi}
      POSTGRES_PASSWORD: ${DIWI_DB_PASSWORD?-define a password please}
    ports:
      - ${DATABASE_PORT:-5432}
    volumes:
      - ./data/database:/var/lib/postgresql/data

  keycloak:
    build:
      context: keycloak
    environment:
      KC_DB: postgres
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_DB_URL_HOST: keycloak_database
      KC_DB_USERNAME: ${KEYCLOAK_DB_USERNAME:-keycloak}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD?-define a password please}
      KC_HOSTNAME_STRICT: false
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD?-define a password please}
    ports:
      - ${KEYCLOAK_PORT:-8080}
    depends_on:
      - keycloak_database
    volumes:
      - ./keycloak/realm-import:/opt/keycloak/data/import
    command: "start --import-realm --optimized"

  keycloak_database:
    image: git.phinion.com/phinion/dependency_proxy/containers/postgres:15
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KEYCLOAK_DB_USERNAME:-keycloak}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    volumes:
      - ./data/keycloak:/var/lib/postgresql/data
