package nl.vng.diwi.services.export.gelderland;

import static nl.vng.diwi.services.DataExchangeExportError.EXPORT_ERROR.MISSING_DATAEXCHANGE_MAPPING;
import static nl.vng.diwi.services.DataExchangeExportError.EXPORT_ERROR.MISSING_MANDATORY_VALUE;
import static nl.vng.diwi.services.DataExchangeExportError.EXPORT_ERROR.MULTIPLE_SINGLE_SELECT_VALUES;
import static nl.vng.diwi.services.DataExchangeExportError.EXPORT_ERROR.NUMERIC_RANGE_VALUE;
import static nl.vng.diwi.services.export.ExportUtil.getOwnershipCategory;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.UUID;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVPrinter;
import org.apache.poi.ss.formula.eval.NotImplementedException;
import org.geojson.Crs;
import org.geojson.Feature;
import org.geojson.FeatureCollection;
import org.geojson.MultiPolygon;
import org.geojson.jackson.CrsType;

import jakarta.ws.rs.core.StreamingOutput;
import lombok.AllArgsConstructor;
import lombok.Data;
import nl.vng.diwi.dal.entities.DataExchangeType;
import nl.vng.diwi.dal.entities.ProjectExportSqlModelExtended;
import nl.vng.diwi.dal.entities.enums.Confidentiality;
import nl.vng.diwi.dal.entities.enums.MutationType;
import nl.vng.diwi.dal.entities.enums.OwnershipType;
import nl.vng.diwi.dal.entities.enums.PlanStatus;
import nl.vng.diwi.dal.entities.enums.PlanType;
import nl.vng.diwi.dal.entities.enums.ProjectPhase;
import nl.vng.diwi.dal.entities.enums.PropertyType;
import nl.vng.diwi.dataexchange.DataExchangeTemplate;
import nl.vng.diwi.dataexchange.DataExchangeTemplate.TemplateProperty;
import nl.vng.diwi.generic.Constants;
import nl.vng.diwi.generic.Json;
import nl.vng.diwi.models.DataExchangePropertyModel;
import nl.vng.diwi.models.PropertyModel;
import nl.vng.diwi.models.RangeSelectDisabledModel;
import nl.vng.diwi.models.SelectModel;
import nl.vng.diwi.models.SingleValueOrRangeModel;
import nl.vng.diwi.security.LoggedUser;
import nl.vng.diwi.services.DataExchangeExportError;
import nl.vng.diwi.services.export.ExportUtil;
import nl.vng.diwi.services.export.ExportUtil.OwnershipValueModel;
import nl.vng.diwi.services.export.OwnershipCategory;
import nl.vng.diwi.services.export.gelderland.GelderlandConstants.DetailPlanningHeaders;
import nl.vng.diwi.services.export.zuidholland.EsriZuidHollandExport.EsriZuidHollandHouseblockProps;

public class GdbGelderlandExport {

    private static final List<String> HOUSE_TYPES = List.of("meergezins", "eengezins", "onbekend");

    private static final List<String> HOUSE_CATEGORIES = List.of(
            "koop1",
            "koop2",
            "koop3",
            "koop4",
            "koop_onb",
            "huur1",
            "huur2",
            "huur3",
            "huur4",
            "huur_onb",
            "onbekend");

    // private static final List<String> DESTROY_OR_BUILD = List.of("", "sloop_");

    static List<String> detailPlanningHeaders;
    static {
        detailPlanningHeaders = new ArrayList<>();
        detailPlanningHeaders.addAll(List.of(
                // "OBJECTID", Is this autogenerated
                "GlobalID",
                "Creator",
                "Created",
                "Editor",
                "Edited",
                "parent_globalid",
                "gemeente",
                "regio",
                "vertrouwelijkheid",
                "jaartal"));
        for (var type : HOUSE_TYPES) {
            for (var cat : HOUSE_CATEGORIES) {
                detailPlanningHeaders.add(type + "_" + cat);
            }

        }
        detailPlanningHeaders.add("bouw_gerealiseerd");
        for (var type : HOUSE_TYPES) {
            for (var cat : HOUSE_CATEGORIES) {
                detailPlanningHeaders.add("sloop_" + type + "_" + cat);
            }

        }
        detailPlanningHeaders.add("sloop_gerealiseerd");
    }

    static Map<String, Object> createEmptyDetailPlanningMap(Integer year) {
        var map = new LinkedHashMap<String, Object>();
        for (var header : GelderlandConstants.DetailPlanningHeaders.values()) {
            map.put(header.name(), "");
        }

        map.put("jaartal", year == null ? "" : year.toString());
        return map;
    }

    @AllArgsConstructor
    @Data
    public static class ProjectExportData {
        Feature planRegistration;
        List<Map<String, Object>> detailPlanning;
    }

    public static StreamingOutput buildExportObject(
            List<ProjectExportSqlModelExtended> projects,
            List<PropertyModel> customProps,
            Map<String, DataExchangePropertyModel> dxPropertiesMap,
            LocalDate exportDate,
            Confidentiality minConfidentiality,
            List<DataExchangeExportError> errors,
            LoggedUser user) {
        FeatureCollection exportObject = new FeatureCollection();
        Crs crs = new Crs();
        crs.setType(CrsType.name);
        String targetCrs = "EPSG:28992";
        crs.getProperties().put("name", targetCrs);
        exportObject.setCrs(crs);

        PropertyModel priceRangeBuyFixedProp = customProps.stream()
                .filter(pfp -> pfp.getName().equals(Constants.FIXED_PROPERTY_PRICE_RANGE_BUY)).findFirst().orElse(null);
        PropertyModel priceRangeRentFixedProp = customProps.stream()
                .filter(pfp -> pfp.getName().equals(Constants.FIXED_PROPERTY_PRICE_RANGE_RENT)).findFirst().orElse(null);
        PropertyModel municipalityFixedProp = customProps.stream()
                .filter(pfp -> pfp.getName().equals(Constants.FIXED_PROPERTY_MUNICIPALITY)).findFirst().orElse(null);

        Map<UUID, PropertyModel> customPropsMap = customProps.stream().collect(Collectors.toMap(PropertyModel::getId, Function.identity()));

        int i = 0;

        try {
            var tempDir = Files.createTempDirectory("GdbGelderlandExport");
            var csvFile = new File(tempDir.toFile(), "DetailPlanning.csv");

            try (CSVPrinter writer = new CSVPrinter(new FileWriter(csvFile), CSVFormat.DEFAULT)) {
                writer.printRecord(Arrays.asList(GelderlandConstants.DetailPlanningHeaders.values()));

                for (var project : projects) {
                    ProjectExportData projectExportData = getProjectFeature(project, customPropsMap, priceRangeBuyFixedProp, priceRangeRentFixedProp,
                            municipalityFixedProp, dxPropertiesMap, minConfidentiality, exportDate, errors, targetCrs, ++i, user);

                    exportObject.add(projectExportData.planRegistration);

                    for (var row : projectExportData.detailPlanning) {
                        writer.printRecord(row.values());
                    }
                }
            }

            var geojsonFile = new File(tempDir.toFile(), "Planregistratie.geojson");
            Json.mapper.writeValue(geojsonFile, exportObject);
            var gdbFile = GdbConversionService.convertToGdb(geojsonFile, csvFile);

            return output -> {
                try (FileInputStream fileInputStream = new FileInputStream(gdbFile)) {
                    fileInputStream.transferTo(output);
                    output.flush();
                }
            };

        } catch (IOException e) {
            throw new RuntimeException(e);
        }

    }

    public static ProjectExportData getProjectFeature(
            ProjectExportSqlModelExtended project,
            Map<UUID, PropertyModel> customPropsMap,
            PropertyModel priceRangeBuyFixedProp,
            PropertyModel priceRangeRentFixedProp,
            PropertyModel municipalityFixedProp,
            Map<String, DataExchangePropertyModel> dxPropertiesMap,
            Confidentiality minConfidentiality,
            LocalDate exportDate,
            List<DataExchangeExportError> errors,
            String targetCrs,
            Integer objectId,
            LoggedUser user) {

        Feature feature = new Feature();

        MultiPolygon multiPolygon = ExportUtil.createPolygonForProject(project.getGeometries(), targetCrs, project.getProjectId());
        if (!multiPolygon.getCoordinates().isEmpty()) {
            feature.setGeometry(multiPolygon);
        }

        feature.setProperty("OBJECTID", objectId); // Is this needed? Or autogenerated?
        feature.setProperty("GlobalID", project.getProjectId());

        feature.setProperty("Created", project.getCreation_date());
        feature.setProperty("Editor", user.getFirstName() + " " + user.getLastName());
        feature.setProperty("Edited", project.getLast_edit_date());

        feature.setProperty("plannaam", project.getName());
        feature.setProperty("provincie", "Gelderland");

        feature.setProperty("vertrouwelijkheid", mapConfidentiality(project.getConfidentiality()));

        feature.setProperty("oplevering_eerste", getFirstDelivery(project));
        feature.setProperty("oplevering_laatste", getLastDelivery(project));
        feature.setProperty("plantype", mapPlanType(project.getPlanType()));
        feature.setProperty("projectfase", mapProjectPhase(project.getProjectPhase()));
        feature.setProperty("status_planologisch", mapPlanStatus(project.getPlanningPlanStatus()));

        feature.setProperty("koppelid", project.getProjectId());

        // klopt_geom // has note check with province
        // SHAPE_Length // Auto generated?
        // SHAPE_Area // Auto generated?
        var detailYearMap = new TreeMap<Integer, Map<String, Object>>();
        var sums = calculateAggregations(
                project,
                exportDate,
                priceRangeBuyFixedProp,
                priceRangeRentFixedProp,
                detailYearMap,
                errors);

        // Add project level sums to object
        for (var sum : sums.entrySet()) {
            feature.setProperty(sum.getKey(), sum.getValue());
        }

        feature.setProperty("overkoepelende_plan_id", null);
        feature.setProperty("overkoepelende_plan_naam", null);

        // custom props
        Map<UUID, String> projectTextCustomProps = project.getTextProperties().stream()
                .collect(Collectors.toMap(
                        ProjectExportSqlModelExtended.TextPropertyModel::getPropertyId,
                        ProjectExportSqlModelExtended.TextPropertyModel::getTextValue));
        Map<UUID, SingleValueOrRangeModel<BigDecimal>> projectNumericCustomProps = project.getNumericProperties().stream()
                .collect(Collectors.toMap(
                        ProjectExportSqlModelExtended.NumericPropertyModel::getPropertyId,
                        ProjectExportSqlModelExtended.NumericPropertyModel::getSingleValueOrRangeModel));
        Map<UUID, List<UUID>> projectCategoricalCustomProps = project.getCategoryProperties().stream()
                .collect(Collectors.toMap(
                        ProjectExportSqlModelExtended.CategoryPropertyModel::getPropertyId,
                        ProjectExportSqlModelExtended.CategoryPropertyModel::getOptionValues));

        for (var templateProperty : DataExchangeTemplate.templates.get(DataExchangeType.GDB_GELDERLAND).getProperties()) {
            var prop = templateProperty.getName();
            DataExchangePropertyModel dxPropertyModel = dxPropertiesMap.get(prop);
            addMappedProperty(
                    project,
                    customPropsMap,
                    dxPropertiesMap,
                    errors,
                    feature,
                    projectTextCustomProps,
                    projectCategoricalCustomProps,
                    projectNumericCustomProps,
                    prop,
                    templateProperty,
                    dxPropertyModel);
        }

        // Add detail planning pzh style
        List<GdbGelderlandHouseblockExportModel> houseblockExportModels = project.getHouseblocks().stream()
                .map(h -> new GdbGelderlandHouseblockExportModel(project.getProjectId(), h, priceRangeBuyFixedProp, priceRangeRentFixedProp, errors)).toList();
        List<Map<String, Object>> houseblockProperties = getHouseblockProperties(houseblockExportModels);

        for (var ba : houseblockProperties) {
            var map = detailYearMap.get(ba.get(DetailPlanningHeaders.jaartal.name()));
            for (var value: ba.entrySet()) {
                map.put(value.getKey(), value.getValue());
            }
        }

        // Add project level info to detail planning
        for (var detailPlanning : detailYearMap.values()) {
            detailPlanning.put("Creator", user.getFirstName() + " " + user.getLastName());
            detailPlanning.put("Created", project.getCreation_date().toString());
            detailPlanning.put("Editor", user.getFirstName() + " " + user.getLastName());
            detailPlanning.put("Edited", project.getLast_edit_date().toString());
            detailPlanning.put("parent_globalid", project.getProjectId().toString());
            detailPlanning.put("gemeente", feature.getProperty("gemeente"));
            detailPlanning.put("regio", feature.getProperty("regio"));
            detailPlanning.put("vertrouwelijkheid", mapConfidentiality(project.getConfidentiality()));
        }

        return new ProjectExportData(feature, detailYearMap.values().stream().toList());
    }

    private static Map<String, Object> calculateAggregations(
            ProjectExportSqlModelExtended project,
            LocalDate exportDate,
            PropertyModel priceRangeBuyFixedProp,
            PropertyModel priceRangeRentFixedProp,
            Map<Integer, Map<String, Object>> detailYearMap,
            List<DataExchangeExportError> errors) {
        int Totaal_aantal_huurwoningen_corporatie = 0;
        int Totaal_bouw = 0;
        int Totaal_gerealiseerd = 0;
        int Totaal_resterend = 0;
        int Totaal_sloop = 0;
        int Totaal_sloop_gerealiseerd = 0;
        int Totaal_sloop_resterend = 0;
        int Totaal_netto = 0;
        int Totaal_netto_gerealiseerd = 0;
        int Totaal_netto_resterend = 0;
        int Totaal_eengezins_resterend = 0;
        int Totaal_meergezins_resterend = 0;
        int Totaal_type_onbekend_resterend = 0;
        int Totaal_koop_resterend = 0;
        int Totaal_huur_resterend = 0;
        int Totaal_koop_huur_onbekend_resterend = 0;
        int Totaal_koop1 = 0;
        int Totaal_koop2 = 0;
        int Totaal_koop3 = 0;
        int Totaal_koop4 = 0;
        int Totaal_koop_onbekend = 0;
        int Totaal_huur1 = 0;
        int Totaal_huur2 = 0;
        int Totaal_huur3 = 0;
        int Totaal_huur4 = 0;
        int Totaal_huur_onbekend = 0;
        int Totaal_eigendom_onbekend = 0;
        int aantal_middenhuur_corporatie = 0;

        for (var b : project.getHouseblocks()) {
            var detailMap = detailYearMap.computeIfAbsent(b.getDeliveryYear(), GdbGelderlandExport::createEmptyDetailPlanningMap);
            detailMap.put("GlobalID", b.getHouseblockId().toString());

            final boolean gerealiseerd = b.getEndDate().isBefore(exportDate);
            final boolean bouw = b.getMutationKind() == MutationType.CONSTRUCTION;
            final int bouwFactor = bouw ? 1 : -1;

            // totals for construction and for house types (single family, etc)
            if (bouw) {
                Totaal_bouw += b.getMutationAmount();
                if (gerealiseerd) {
                    Totaal_gerealiseerd += b.getMutationAmount();
                } else {
                    int eengezinswoning = b.getEengezinswoning() == null ? 0 : b.getEengezinswoning();
                    int meergezinswoning = b.getMeergezinswoning() == null ? 0 : b.getMeergezinswoning();

                    Totaal_resterend += b.getMutationAmount();
                    Totaal_meergezins_resterend += meergezinswoning;
                    Totaal_eengezins_resterend += eengezinswoning;
                    Totaal_type_onbekend_resterend = b.getMutationAmount() - meergezinswoning - eengezinswoning;
                }
            } else {
                Totaal_sloop += b.getMutationAmount();
                if (gerealiseerd) {
                    Totaal_sloop_gerealiseerd += b.getMutationAmount();
                } else {
                    Totaal_sloop_resterend += b.getMutationAmount();
                }
            }

            int huur_resterend = 0;
            int koop_resterend = 0;

            // totals for ownership
            for (var o : b.getOwnershipValueList()) {
                var model = createOwnershipValueModel(
                        project.getProjectId(),
                        b,
                        priceRangeBuyFixedProp,
                        priceRangeRentFixedProp,
                        errors,
                        GelderlandConstants.priceRangeMap,
                        o);

                switch (model.getOwnershipCategory()) {
                case huur1 -> Totaal_huur1 += bouwFactor * model.getAmount();
                case huur2 -> Totaal_huur2 += bouwFactor * model.getAmount();
                case huur3 -> Totaal_huur3 += bouwFactor * model.getAmount();
                case huur4 -> Totaal_huur4 += bouwFactor * model.getAmount();
                case huur_onb -> Totaal_huur_onbekend += bouwFactor * model.getAmount();

                case koop1 -> Totaal_koop1 += bouwFactor * model.getAmount();
                case koop2 -> Totaal_koop2 += bouwFactor * model.getAmount();
                case koop3 -> Totaal_koop3 += bouwFactor * model.getAmount();
                case koop4 -> Totaal_koop4 += bouwFactor * model.getAmount();
                case koop_onb -> Totaal_koop_onbekend += bouwFactor * model.getAmount();
                }

                if (o.getOwnershipType() == OwnershipType.HUURWONING_WONINGCORPORATIE) {
                    Totaal_aantal_huurwoningen_corporatie += o.getOwnershipAmount();

                    if (model.getOwnershipCategory() == OwnershipCategory.huur2 ||
                            model.getOwnershipCategory() == OwnershipCategory.huur3) {
                        aantal_middenhuur_corporatie += bouwFactor * model.getAmount();
                    }
                }

                if (o.getOwnershipType() == OwnershipType.HUURWONING_WONINGCORPORATIE
                        || o.getOwnershipType() == OwnershipType.HUURWONING_PARTICULIERE_VERHUURDER) {
                    if (!gerealiseerd) {
                        huur_resterend += bouwFactor * o.getOwnershipAmount();
                        Totaal_huur_resterend += bouwFactor * o.getOwnershipAmount();
                    }
                } else if (o.getOwnershipType() == OwnershipType.KOOPWONING) {
                    if (!gerealiseerd) {
                        koop_resterend += bouwFactor * o.getOwnershipAmount();
                        Totaal_koop_resterend += bouwFactor * o.getOwnershipAmount();
                    }
                }
            }
            if (!gerealiseerd) {
                int resterend = bouwFactor * b.getMutationAmount();
                Totaal_koop_huur_onbekend_resterend += resterend - huur_resterend - koop_resterend;
            }
        }

        Totaal_netto = Totaal_bouw - Totaal_sloop;
        Totaal_netto_gerealiseerd = Totaal_gerealiseerd - Totaal_sloop_gerealiseerd;
        Totaal_netto_resterend = Totaal_resterend - Totaal_sloop_resterend;

        var map = new HashMap<String, Object>();
        map.put("aantal_huurwoningen_corporatie", Totaal_aantal_huurwoningen_corporatie);
        map.put("Totaal_bouw", Totaal_bouw);
        map.put("Totaal_gerealiseerd", Totaal_gerealiseerd);
        map.put("Totaal_resterend", Totaal_resterend);
        map.put("Totaal_sloop", Totaal_sloop);
        map.put("Totaal_sloop_gerealiseerd", Totaal_sloop_gerealiseerd);
        map.put("Totaal_sloop_resterend", Totaal_sloop_resterend);
        map.put("Totaal_netto", Totaal_netto);
        map.put("Totaal_netto_gerealiseerd", Totaal_netto_gerealiseerd);
        map.put("Totaal_netto_resterend", Totaal_netto_resterend);
        map.put("Totaal_eengezins_resterend", Totaal_eengezins_resterend);
        map.put("Totaal_meergezins_resterend", Totaal_meergezins_resterend);
        map.put("Totaal_type_onbekend_resterend", Totaal_type_onbekend_resterend);
        map.put("Totaal_koop_resterend", Totaal_koop_resterend);
        map.put("Totaal_huur_resterend", Totaal_huur_resterend);
        map.put("Totaal_koop_huur_onbekend_resterend", Totaal_koop_huur_onbekend_resterend);
        map.put("Totaal_koop1", Totaal_koop1);
        map.put("Totaal_koop2", Totaal_koop2);
        map.put("Totaal_koop3", Totaal_koop3);
        map.put("Totaal_koop4", Totaal_koop4);
        map.put("Totaal_koop_onbekend", Totaal_koop_onbekend);
        map.put("Totaal_huur1", Totaal_huur1);
        map.put("Totaal_huur2", Totaal_huur2);
        map.put("Totaal_huur3", Totaal_huur3);
        map.put("Totaal_huur4", Totaal_huur4);
        map.put("Totaal_huur_onbekend", Totaal_huur_onbekend);
        map.put("Totaal_eigendom_onbekend", Totaal_eigendom_onbekend);
        map.put("aantal_middenhuur_corporatie", aantal_middenhuur_corporatie);

        return map;
    }

    private static String mapPlanStatus(List<PlanStatus> planningPlanStatus) {
        if (planningPlanStatus.isEmpty()) {
            return "Onbekend";
        }
        var status = planningPlanStatus.get(0);
        return switch (status) {
        case _1A_ONHERROEPELIJK -> "1A. Onherroepelijk";
        case _1B_ONHERROEPELIJK_MET_UITWERKING_NODIG -> "1B. Onherroepelijk, uitwerkingsplicht";
        case _1C_ONHERROEPELIJK_MET_BW_NODIG -> "1C. Onherroepelijk, wijzigingsbevoegdheid";
        case _2A_VASTGESTELD -> "2A. Vastgesteld";
        case _2B_VASTGESTELD_MET_UITWERKING_NODIG -> "2B. Vastgesteld, uitwerkingsplicht";
        case _2C_VASTGESTELD_MET_BW_NODIG -> "2C. Vastgesteld, wijzigingsbevoegdheid";
        case _3_IN_VOORBEREIDING -> "3. In voorbereiding";
        case _4A_OPGENOMEN_IN_VISIE -> "4A. Visie";
        case _4B_NIET_OPGENOMEN_IN_VISIE -> "4B. Idee";
        };
    }

    private static String mapProjectPhase(ProjectPhase projectPhase) {
        if (projectPhase == null) {
            return null;
        }
        return switch (projectPhase) {
        case _2_INITIATIVE -> "1. Initiatief";
        case _3_DEFINITION -> "2. Definitie";
        case _4_DESIGN -> "3. Ontwerp";
        case _5_PREPARATION -> "4. Voorbereiding";
        case _6_REALIZATION -> "5. Realisatie";
        case _7_AFTERCARE -> "6. Nazorg";
        // case -> "7. Afgerond"; // TODO can we find this another way?
        case _1_CONCEPT -> "Onbekend";
        };
    }

    private static String mapPlanType(List<PlanType> planType) {
        if (planType.isEmpty()) {
            return null;
        }
        return switch (planType.get(0)) {
        case HERSTRUCTURERING -> "Herstructurering";
        case PAND_TRANSFORMATIE -> "Pand transformatie";
        case TRANSFORMATIEGEBIED -> "Transformatiegebied";
        case UITBREIDING_OVERIG -> "Uitbreiding overig";
        case UITBREIDING_UITLEG -> "Uitbreiding uitleg";
        case VERDICHTING -> "Verdichting";
        };
    }

    private static LocalDate getFirstDelivery(ProjectExportSqlModelExtended project) {
        return project.getHouseblocks().stream().map(b -> b.getEndDate()).min(LocalDate::compareTo).orElse(null);
    }

    private static LocalDate getLastDelivery(ProjectExportSqlModelExtended project) {
        return project.getHouseblocks().stream().map(b -> b.getEndDate()).max(LocalDate::compareTo).orElse(null);
    }

    private static String mapConfidentiality(Confidentiality confidentiality) {
        if (confidentiality == null) {
            return "";
        }
        return switch (confidentiality) {
        case INTERNAL_CIVIL, INTERNAL_MANAGEMENT, INTERNAL_COUNCIL -> "Gemeente";
        case EXTERNAL_REGIONAL -> "Regio";
        case EXTERNAL_GOVERNMENTAL -> "ProvincieGemeente";
        case PUBLIC -> "Openbaar";
        case PRIVATE -> throw new RuntimeException("Can't export private projects");
        };
    }

    static private OwnershipValueModel createOwnershipValueModel(
            UUID projectUuid,
            ProjectExportSqlModelExtended.HouseblockExportSqlModel sqlModel,
            PropertyModel priceRangeBuyFixedProp,
            PropertyModel priceRangeRentFixedProp,
            List<DataExchangeExportError> errors,
            Map<OwnershipCategory, Long> priceCategoryMap,
            ProjectExportSqlModelExtended.OwnershipValueSqlModel o) {
        OwnershipValueModel oModel = new OwnershipValueModel();
        oModel.setOwnershipType(o.getOwnershipType());
        oModel.setAmount(o.getOwnershipAmount());
        if (o.getOwnershipType() == OwnershipType.KOOPWONING) {
            if (o.getOwnershipValue() != null) {
                oModel.setOwnershipCategory(
                        getOwnershipCategory(o.getOwnershipType(), o.getOwnershipValue(), priceCategoryMap));
            } else if (o.getOwnershipValueRangeMin() != null) {
                oModel.setOwnershipCategory(ExportUtil.getOwnershipCategory(
                        projectUuid,
                        sqlModel.getHouseblockId(),
                        o.getOwnershipType(),
                        o.getOwnershipValueRangeMin(),
                        o.getOwnershipValueRangeMax(),
                        priceCategoryMap,
                        errors));
            } else if (o.getOwnershipRangeCategoryId() != null) {
                RangeSelectDisabledModel rangeOption = priceRangeBuyFixedProp.getRanges().stream()
                        .filter(r -> r.getDisabled() == Boolean.FALSE
                                && r.getId().equals(o.getOwnershipRangeCategoryId()))
                        .findFirst().orElse(null);
                if (rangeOption == null) {
                    oModel.setOwnershipCategory(OwnershipCategory.koop_onb);
                } else {
                    oModel.setOwnershipCategory(ExportUtil.getOwnershipCategory(
                            projectUuid,
                            sqlModel.getHouseblockId(),
                            o.getOwnershipType(),
                            rangeOption.getMin().longValue(),
                            rangeOption.getMax().longValue(),
                            priceCategoryMap,
                            errors));
                }
            } else {
                oModel.setOwnershipCategory(OwnershipCategory.koop_onb);
            }
        } else {
            if (o.getOwnershipRentalValue() != null) {
                oModel.setOwnershipCategory(getOwnershipCategory(o.getOwnershipType(), o.getOwnershipRentalValue(), priceCategoryMap));
            } else if (o.getOwnershipRentalValueRangeMin() != null) {
                oModel.setOwnershipCategory(
                        ExportUtil.getOwnershipCategory(
                                projectUuid,
                                sqlModel.getHouseblockId(),
                                o.getOwnershipType(),
                                o.getOwnershipRentalValueRangeMin(),
                                o.getOwnershipRentalValueRangeMax(),
                                priceCategoryMap,
                                errors));
            } else if (o.getOwnershipRentalRangeCategoryId() != null) {
                RangeSelectDisabledModel rangeOption = priceRangeRentFixedProp.getRanges().stream()
                        .filter(r -> r.getDisabled() == Boolean.FALSE
                                && r.getId().equals(o.getOwnershipRentalRangeCategoryId()))
                        .findFirst().orElse(null);
                if (rangeOption == null) {
                    oModel.setOwnershipCategory(OwnershipCategory.huur_onb);
                } else {
                    oModel.setOwnershipCategory(
                            ExportUtil.getOwnershipCategory(projectUuid,
                                    sqlModel.getHouseblockId(),
                                    o.getOwnershipType(),
                                    rangeOption.getMin().longValue(),
                                    rangeOption.getMax().longValue(),
                                    priceCategoryMap,
                                    errors));
                }
            } else {
                oModel.setOwnershipCategory(OwnershipCategory.huur_onb);
            }
        }
        return oModel;
    }

    /*
     * TODO: Needs to be deduplicated with the version in pzh
     */
    public static void addMappedProperty(
            ProjectExportSqlModelExtended project,
            Map<UUID, PropertyModel> customPropsMap,
            Map<String, DataExchangePropertyModel> dxPropertiesMap,
            List<DataExchangeExportError> errors,
            Feature projectFeature,
            Map<UUID, String> projectTextCustomProps,
            Map<UUID, List<UUID>> projectCategoricalCustomProps,
            Map<UUID, SingleValueOrRangeModel<BigDecimal>> projectNumericCustomProps,
            String propName,
            TemplateProperty templateProperty,
            DataExchangePropertyModel dxPropertyModel) {
        if (dxPropertyModel == null) {
            // TODO: Should we allow it not being set?
            projectFeature.getProperties().put(templateProperty.getName(), "");
        } else if (templateProperty.getPropertyTypes().contains(PropertyType.TEXT)) {
            // If it accepts a text property it should be able to map a category to it
            if (projectTextCustomProps.containsKey(dxPropertyModel.getCustomPropertyId())) {
                addProjectTextCustomProperty(project.getProjectId(), projectFeature, templateProperty, dxPropertiesMap, projectTextCustomProps, errors);
            } else if (projectCategoricalCustomProps.containsKey(dxPropertyModel.getCustomPropertyId())) {
                addProjectCategoricalCustomPropertyAsText(project.getProjectId(), projectFeature, templateProperty, dxPropertiesMap,
                        projectCategoricalCustomProps, customPropsMap, errors);
            } else {
                projectFeature.getProperties().put(propName, null);
            }
        } else if (templateProperty.getPropertyTypes().containsAll(List.of(PropertyType.NUMERIC))) {
            addProjectNumericCustomProperty(
                    project.getProjectId(),
                    projectFeature,
                    templateProperty,
                    dxPropertiesMap,
                    projectNumericCustomProps,
                    errors);
        } else if (templateProperty.getPropertyTypes().containsAll(List.of(PropertyType.CATEGORY))) {
            addProjectCategoricalCustomProperty(
                    project.getProjectId(),
                    projectFeature,
                    templateProperty,
                    dxPropertiesMap,
                    projectCategoricalCustomProps,
                    errors);
        } else {
            throw new NotImplementedException("Combination of types not implemented");
        }
    }

    private static void addProjectTextCustomProperty(UUID projectUuid, Feature projectFeature, DataExchangeTemplate.TemplateProperty templateProperty,
            Map<String, DataExchangePropertyModel> dxPropertiesMap, Map<UUID, String> projectTextCustomProps,
            List<DataExchangeExportError> errors) {
        DataExchangePropertyModel dataExchangePropertyModel = dxPropertiesMap.get(templateProperty.getName());
        UUID customPropUuid = dataExchangePropertyModel.getCustomPropertyId();
        String ezhValue = null;
        if (customPropUuid == null) {
            if (dataExchangePropertyModel.getMandatory()) {
                errors.add(new DataExchangeExportError(null, templateProperty.getName(), MISSING_DATAEXCHANGE_MAPPING));
            }
        } else if (projectTextCustomProps.containsKey(customPropUuid)) {
            ezhValue = projectTextCustomProps.get(customPropUuid);
        } else if (templateProperty.getMandatory()) {
            errors.add(new DataExchangeExportError(projectUuid, templateProperty.getName(), MISSING_MANDATORY_VALUE));
        }
        projectFeature.getProperties().put(templateProperty.getName(), ezhValue);
    }

    private static void addProjectCategoricalCustomPropertyAsText(UUID projectUuid, Feature projectFeature, TemplateProperty templateProperty,
            Map<String, DataExchangePropertyModel> dxPropertiesMap, Map<UUID, List<UUID>> projectCategoricalCustomProps,
            Map<UUID, PropertyModel> customPropsMap, List<DataExchangeExportError> errors) {
        DataExchangePropertyModel dataExchangePropertyModel = dxPropertiesMap.get(templateProperty.getName());
        UUID customPropUuid = dataExchangePropertyModel.getCustomPropertyId();
        String ezhValue = null;
        if (customPropUuid == null) {
            if (dataExchangePropertyModel.getMandatory()) {
                errors.add(new DataExchangeExportError(null, templateProperty.getName(), MISSING_DATAEXCHANGE_MAPPING));
            }
        } else if (projectCategoricalCustomProps.containsKey(customPropUuid)) {
            UUID optionUuid = projectCategoricalCustomProps.get(customPropUuid).get(0);
            PropertyModel propertyModel = customPropsMap.get(customPropUuid);
            ezhValue = propertyModel.getCategories().stream().filter(o -> o.getDisabled() == Boolean.FALSE && o.getId().equals(optionUuid))
                    .map(SelectModel::getName).findFirst().orElse(null);
        } else if (templateProperty.getMandatory()) {
            errors.add(new DataExchangeExportError(projectUuid, templateProperty.getName(), MISSING_MANDATORY_VALUE));
        }
        projectFeature.getProperties().put(templateProperty.getName(), ezhValue);

    }

    private static void addProjectCategoricalCustomProperty(UUID projectUuid, Feature projectFeature, DataExchangeTemplate.TemplateProperty templateProperty,
            Map<String, DataExchangePropertyModel> dxPropertiesMap, Map<UUID, List<UUID>> projectCategoricalCustomProps,
            List<DataExchangeExportError> errors) {
        DataExchangePropertyModel dataExchangePropertyModel = dxPropertiesMap.get(templateProperty.getName());
        List<String> ezhValue = new ArrayList<>();
        if (dataExchangePropertyModel == null) {
            errors.add(new DataExchangeExportError(null, templateProperty.getName(), MISSING_DATAEXCHANGE_MAPPING));
        } else if (projectCategoricalCustomProps.containsKey(dataExchangePropertyModel.getCustomPropertyId())) {
            List<UUID> projectCategoryOptions = projectCategoricalCustomProps.get(dataExchangePropertyModel.getCustomPropertyId());
            for (UUID option : projectCategoryOptions) {
                dataExchangePropertyModel.getOptions().forEach(dxOption -> {
                    if (dxOption.getPropertyCategoryValueIds().contains(option)) {
                        ezhValue.add(dxOption.getName());
                    }
                });
            }
        }

        if (templateProperty.getMandatory() && ezhValue.isEmpty()) {
            errors.add(new DataExchangeExportError(projectUuid, templateProperty.getName(), MISSING_MANDATORY_VALUE));
        }
        if (templateProperty.getSingleSelect() && ezhValue.size() > 1) {
            errors.add(new DataExchangeExportError(projectUuid, templateProperty.getName(), MULTIPLE_SINGLE_SELECT_VALUES));
        }

        if (templateProperty.getSingleSelect()) {
            projectFeature.getProperties().put(templateProperty.getName(), ezhValue.isEmpty() ? null : ezhValue.get(0));
        } else {
            projectFeature.getProperties().put(templateProperty.getName(), ezhValue.isEmpty() ? null : ezhValue);
        }
    }

    private static BigDecimal addProjectNumericCustomProperty(UUID projectUuid, Feature projectFeature, DataExchangeTemplate.TemplateProperty templateProperty,
            Map<String, DataExchangePropertyModel> dxPropertiesMap, Map<UUID, SingleValueOrRangeModel<BigDecimal>> projectNumericCustomProps,
            List<DataExchangeExportError> errors) {
        DataExchangePropertyModel dataExchangePropertyModel = dxPropertiesMap.get(templateProperty.getName());
        UUID customPropUuid = dataExchangePropertyModel.getCustomPropertyId();
        BigDecimal ezhValue = null;
        if (customPropUuid == null) {
            if (dataExchangePropertyModel.getMandatory()) {
                errors.add(new DataExchangeExportError(null, templateProperty.getName(), MISSING_DATAEXCHANGE_MAPPING));
            }
        } else if (projectNumericCustomProps.containsKey(customPropUuid)) {
            var numericVal = projectNumericCustomProps.get(customPropUuid);
            if (numericVal.getValue() != null) {
                ezhValue = numericVal.getValue();
            } else if (numericVal.getMin() != null) {
                errors.add(new DataExchangeExportError(projectUuid, templateProperty.getName(), NUMERIC_RANGE_VALUE));
            }
        } else if (templateProperty.getMandatory()) {
            errors.add(new DataExchangeExportError(projectUuid, templateProperty.getName(), MISSING_MANDATORY_VALUE));
        }
        projectFeature.getProperties().put(templateProperty.getName(), ezhValue);

        return ezhValue;
    }

    private static List<Map<String, Object>> getHouseblockProperties(List<GdbGelderlandHouseblockExportModel> houseblocks) {

        Map<Integer, List<GdbGelderlandHouseblockExportModel>> houseblocksByDeliveryYear = new HashMap<>();
        houseblocks.forEach(houseblock -> {
            if (!houseblocksByDeliveryYear.containsKey(houseblock.getDeliveryYear())) {
                houseblocksByDeliveryYear.put(houseblock.getDeliveryYear(), new ArrayList<>());
            }
            houseblocksByDeliveryYear.get(houseblock.getDeliveryYear()).add(houseblock);
        });

        List<Map<String, Object>> allHouseblockProperties = new ArrayList<>();

        List<Integer> deliveryYears = houseblocksByDeliveryYear.keySet().stream().sorted().toList();
        deliveryYears.forEach(deliveryYear -> {
            allHouseblockProperties.add(getHouseblockPropertiesForDeliveryYear(houseblocksByDeliveryYear.get(deliveryYear)));
        });

        return allHouseblockProperties;
    }

    private static Map<String, Object> getHouseblockPropertiesForDeliveryYear(List<GdbGelderlandHouseblockExportModel> houseblockExportModels) {

        Map<String, Object> hbPropsByDeliveryYear = new LinkedHashMap<>();

        GdbGelderlandHouseblockModel constructionHbTotals = new GdbGelderlandHouseblockModel();
        GdbGelderlandHouseblockModel demolitionHbTotals = new GdbGelderlandHouseblockModel();

        houseblockExportModels.forEach(h -> {
            if ((h.getMutationKind() == MutationType.CONSTRUCTION)) {
                constructionHbTotals.addHouseblockData(h);
            } else {
                demolitionHbTotals.addHouseblockData(h);
            }
        });

        Map<EsriZuidHollandHouseblockProps, Integer> constructionValuesMap = constructionHbTotals.calculateHouseTypeOwnershipValuesMap();
        Map<EsriZuidHollandHouseblockProps, Integer> demolitionValuesMap = demolitionHbTotals.calculateHouseTypeOwnershipValuesMap();

        for (var prop : EsriZuidHollandHouseblockProps.values()) {
            switch (prop) {
            case jaartal -> hbPropsByDeliveryYear.put(prop.name(), houseblockExportModels.get(0).getDeliveryYear());

            case meergezins_koop1 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop1));
            case meergezins_koop2 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop2));
            case meergezins_koop3 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop3));
            case meergezins_koop4 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop4));
            case meergezins_koop_onb -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop_onb));
            case meergezins_huur1 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur1));
            case meergezins_huur2 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur2));
            case meergezins_huur3 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur3));
            case meergezins_huur4 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur4));
            case meergezins_huur_onb -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur_onb));
            case meergezins_onbekend -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_onbekend));

            case eengezins_koop1 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop1));
            case eengezins_koop2 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop2));
            case eengezins_koop3 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop3));
            case eengezins_koop4 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop4));
            case eengezins_koop_onb -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop_onb));
            case eengezins_huur1 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur1));
            case eengezins_huur2 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur2));
            case eengezins_huur3 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur3));
            case eengezins_huur4 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur4));
            case eengezins_huur_onb -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur_onb));
            case eengezins_onbekend -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_onbekend));

            case onbekend_koop1 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop1));
            case onbekend_koop2 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop2));
            case onbekend_koop3 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop3));
            case onbekend_koop4 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop4));
            case onbekend_koop_onb -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop_onb));
            case onbekend_huur1 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur1));
            case onbekend_huur2 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur2));
            case onbekend_huur3 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur3));
            case onbekend_huur4 -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur4));
            case onbekend_huur_onb -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur_onb));
            case onbekend_onbekend -> hbPropsByDeliveryYear.put(prop.name(), constructionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_onbekend));

            case bouw_gerealiseerd ->
                hbPropsByDeliveryYear.put(prop.name(), LocalDate.now().getYear() < houseblockExportModels.get(0).getDeliveryYear() ? "Ja" : "Nee");

            case sloop_meergezins_koop1 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop1));
            case sloop_meergezins_koop2 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop2));
            case sloop_meergezins_koop3 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop3));
            case sloop_meergezins_koop4 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop4));
            case sloop_meergezins_koop_onb ->
                hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_koop_onb));
            case sloop_meergezins_huur1 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur1));
            case sloop_meergezins_huur2 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur2));
            case sloop_meergezins_huur3 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur3));
            case sloop_meergezins_huur4 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur4));
            case sloop_meergezins_huur_onb ->
                hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_huur_onb));
            case sloop_meergezins_onbekend ->
                hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.meergezins_onbekend));

            case sloop_eengezins_koop1 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop1));
            case sloop_eengezins_koop2 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop2));
            case sloop_eengezins_koop3 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop3));
            case sloop_eengezins_koop4 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop4));
            case sloop_eengezins_koop_onb -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_koop_onb));
            case sloop_eengezins_huur1 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur1));
            case sloop_eengezins_huur2 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur2));
            case sloop_eengezins_huur3 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur3));
            case sloop_eengezins_huur4 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur4));
            case sloop_eengezins_huur_onb -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_huur_onb));
            case sloop_eengezins_onbekend -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.eengezins_onbekend));

            case sloop_onbekend_koop1 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop1));
            case sloop_onbekend_koop2 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop2));
            case sloop_onbekend_koop3 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop3));
            case sloop_onbekend_koop4 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop4));
            case sloop_onbekend_koop_onb -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_koop_onb));
            case sloop_onbekend_huur1 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur1));
            case sloop_onbekend_huur2 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur2));
            case sloop_onbekend_huur3 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur3));
            case sloop_onbekend_huur4 -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur4));
            case sloop_onbekend_huur_onb -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_huur_onb));
            case sloop_onbekend_onbekend -> hbPropsByDeliveryYear.put(prop.name(), demolitionValuesMap.get(EsriZuidHollandHouseblockProps.onbekend_onbekend));

            case sloop_gerealiseerd ->
                hbPropsByDeliveryYear.put(prop.name(), LocalDate.now().getYear() < houseblockExportModels.get(0).getDeliveryYear() ? "Ja" : "Nee");
            }
        }

        return hbPropsByDeliveryYear;

    }
}
