ALTER TYPE diwi_testset.confidentiality RENAME VALUE 'PRIVE' TO 'PRIVATE';

ALTER TYPE diwi_testset.confidentiality RENAME VALUE 'INTERN_UITVOERING' TO 'INTERNAL_CIVIL';
ALTER TYPE diwi_testset.confidentiality RENAME VALUE 'INTERN_RAPPORTAGE' TO 'INTERNAL_MANAGEMENT';
ALTER TYPE diwi_testset.confidentiality RENAME VALUE 'EXTERN_RAPPORTAGE' TO 'EXTERNAL_REGIONAL';
ALTER TYPE diwi_testset.confidentiality RENAME VALUE 'OPENBAAR' TO 'PUBLIC';

ALTER TYPE diwi_testset.confidentiality ADD VALUE 'INTERNAL_COUNCIL' BEFORE 'EXTERNAL_REGIONAL';
ALTER TYPE diwi_testset.confidentiality ADD VALUE 'EXTERNAL_GOVERNMENTAL' AFTER 'EXTERNAL_REGIONAL';

