ALTER TYPE diwi_testset.project_phase RENAME VALUE '_1_INITIATIEFFASE' TO '_2_INITIATIVE';
ALTER TYPE diwi_testset.project_phase RENAME VALUE '_2_PROJECTFASE' TO '_3_DEFINITION';
ALTER TYPE diwi_testset.project_phase RENAME VALUE '_3_VERGUNNINGSFASE' TO '_5_PREPARATION';
ALTER TYPE diwi_testset.project_phase RENAME VALUE '_4_REALISATIEFASE' TO '_6_REALIZATION';
ALTER TYPE diwi_testset.project_phase RENAME VALUE '_5_OPLEVERINGSFASE' TO '_7_AFTERCARE';

ALTER TYPE diwi_testset.project_phase ADD VALUE '_1_CONCEPT' BEFORE '_2_INITIATIVE';
ALTER TYPE diwi_testset.project_phase ADD VALUE '_4_DESIGN' BEFORE '_5_PREPARATION';

