package nl.vng.diwi.dal.entities.enums;

public enum PlanStatus {

    //DO NOT CHANGE THE ORDER

    _4A_OPGENOMEN_IN_VISIE,
    _4B_NIET_OPGENOMEN_IN_VISIE,
    _3_IN_VOORBEREIDING,
    _2A_VASTGESTELD,
    _2B_VASTGESTELD_MET_UITWERKING_NODIG,
    _2C_VASTGESTELD_MET_BW_NODIG,
    _1A_ONHERROEPELIJK,
    _1B_ONHERROEPELIJK_MET_UITWERKING_NODIG,
    _1C_ONHERROEPELIJK_MET_BW_NODIG;
}
